"""initial models

Revision ID: 887214cfa169
Revises: 
Create Date: 2026-04-07 22:34:24.699704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887214cfa169'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escuelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escuelas_id'), 'escuelas', ['id'], unique=False)
    op.create_table('grados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grados_id'), 'grados', ['id'], unique=False)
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('clase', 'recreo', 'comedor', name='tipomodulo'), nullable=True),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_id'), 'modulos', ['id'], unique=False)
    op.create_table('profesores_curriculares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('modulos_cargo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesores_curriculares_id'), 'profesores_curriculares', ['id'], unique=False)
    op.create_table('asignaciones_curriculares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('modulos_semanales', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores_curriculares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_curriculares_id'), 'asignaciones_curriculares', ['id'], unique=False)
    op.create_table('disponibilidad_profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', name='diasemana'), nullable=False),
    sa.Column('modulos_ese_dia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores_curriculares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidad_profesores_id'), 'disponibilidad_profesores', ['id'], unique=False)
    op.create_table('maestras_de_grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grado_id')
    )
    op.create_index(op.f('ix_maestras_de_grado_id'), 'maestras_de_grado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maestras_de_grado_id'), table_name='maestras_de_grado')
    op.drop_table('maestras_de_grado')
    op.drop_index(op.f('ix_disponibilidad_profesores_id'), table_name='disponibilidad_profesores')
    op.drop_table('disponibilidad_profesores')
    op.drop_index(op.f('ix_asignaciones_curriculares_id'), table_name='asignaciones_curriculares')
    op.drop_table('asignaciones_curriculares')
    op.drop_index(op.f('ix_profesores_curriculares_id'), table_name='profesores_curriculares')
    op.drop_table('profesores_curriculares')
    op.drop_index(op.f('ix_modulos_id'), table_name='modulos')
    op.drop_table('modulos')
    op.drop_index(op.f('ix_grados_id'), table_name='grados')
    op.drop_table('grados')
    op.drop_index(op.f('ix_escuelas_id'), table_name='escuelas')
    op.drop_table('escuelas')
    # ### end Alembic commands ###
